version: '3'

volumes:
  mqtt:

services:
  mqtt:
    image: eclipse-mosquitto
    volumes:
      - mqtt:/mosquitto/data
      - ./mqtt/mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
    ports:
      - 127.0.0.1:9001:9001
