version: '3'

volumes:
  mqtt:
  datastore:

services:
  mqtt:
    image: eclipse-mosquitto
    volumes:
      - mqtt:/mosquitto/data
      - ./mqtt/mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
    ports:
      - 127.0.0.1:1883:1883
      - 127.0.0.1:9001:9001
  datastore:
    image: singularities/datastore-emulator
    environment:
      - DATASTORE_PROJECT_ID=behrsin-iot
      - DATASTORE_LISTEN_ADDRESS=0.0.0.0:8081
    volumes:
      - datastore:/opt/data
    ports:
      - 127.0.0.1:8081:8081
