# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'z3js' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for z3js
  pod 'TrustKit'

  target 'z3jsTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'z3js-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for z3js-tvOS

  target 'z3js-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
