version: '3'

services:
  build:
    build: .
    volumes:
      - /dev:/dev
      - ../dist:/dist
      - ./customize.sh:/source/customize.sh:ro
      - ./fs:/source/fs:ro
      - ./fs.dev:/source/fs.dev:ro
      - ./scripts:/source/scripts:ro
      - ../:/repo:ro
      - ${HOME}/.ssh:/root/.ssh:ro
    privileged: true
    network_mode: host
    environment:
      - ENV=${ENV:-production}
    tty: true
